apiVersion: v1
kind: Service
metadata:
  name: mysqlserver-messages
  namespace: dreamrealm
  labels:
    app: mysqlserver-messages
    tier: backend
spec:
  selector:
    app: mysqlserver-messages
  ports:
    - protocol: TCP
      name: "3306"
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlserver-messages
  namespace: dreamrealm
spec:
  selector:
    matchLabels:
      app: mysqlserver-messages
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqlserver-messages
        tier: backend
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: example
            - name: MYSQL_TCP_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: messages