apiVersion: v1
kind: Service
metadata:
  name: messages
  namespace: dreamrealm
  labels:
    app: messages
    tier: backend
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: messages
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages
  namespace: dreamrealm
spec:
  selector:
    matchLabels:
      app: messages
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: messages
        tier: backend
    spec:
      containers:
        - name: messages
          image: docker.io/dreamrealm/messagemicroservice:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081